### ISSUE TITLE
Get BIDS license for UMLS so we can share credentials for API access

### ISSUE THREAD

**Issue by Sigfried** [HOT-Ecosystem/ValueSet-Tools#17]
Oh, @DaveraGabriel, you're talking about VSAC access, not JHU OMOP access. We should move that to a different issue. I already made the mistake of confusing the two in this thread.

_Originally posted by @Sigfried in https://github.com/HOT-Ecosystem/ValueSet-Tools/issues/14#issuecomment-1011233079_

**Comment by Sigfried** [comment]
Never mind. I was making it too complicated. @joeflack4 can handle it: https://github.com/HOT-Ecosystem/ValueSet-Tools/issues/14#issuecomment-1011232105

**Comment by joeflack4** [comment]
I've started working on this. So far what I think we'll have will be, with my PII as the tentative/interim recovery email/phone:

### 1. New UMLS account
Username: bidsshared
Connected email account: bids.shared@gmail.com
Connected phone: (joe's phone)

### 2. New Gmail account
Account: bids.shared@gmail.com
Recovery email: (joe's email)
Recovery phone: (joe's phone)

**Comment by Sigfried** [comment]
Great, @joeflack4!! In addition to sharing those accounts (you've probably already thought of this), you can make a .env file and share it securely with us to put in our copies of this python application.

**Comment by joeflack4** [comment]
A very good idea!

For now, I've shared the current API key (my own) on the BIDS one drive: https://livejohnshopkins-my.sharepoint.com/personal/jflack1_jh_edu/_layouts/15/onedrive.aspx?id=%2Fsites%2FBiomedicalInformaticsandDataScience%2FShared%20Documents%2FProjects%2FCD2H%2C%20N3C%2C%20PASC%2FValueSet%20Tools%2Fenv&listurl=https%3A%2F%2Flivejohnshopkins%2Esharepoint%2Ecom%2Fsites%2FBiomedicalInformaticsandDataScience%2FShared%20Documents&viewid=51daccc9%2D8479%2D4ef4%2Da7bf%2D65b689881f3a

I also included instructions on how to get that in the setup part of the tooling documentation on the GitHub home page: https://github.com/HOT-Ecosystem/ValueSet-Tools#set-up--installation

When this new account is proved, i'll update the `.env` file on OneDrive w/ the new API Key.

**Comment by joeflack4** [comment]
Account has been approved, and `.env` file updated, so I am now closing.
