### ISSUE TITLE
Move issue tracking out of GitHub Issues and into Jira

### ISSUE THREAD

**Issue by Sigfried** [HOT-Ecosystem/ValueSet-Tools#21]
Have created a new [Jira story](https://n3c-help.atlassian.net/browse/N3CDIH-86) to hold these issues. @manna_tmp would prefer to do issue tracking there, which is reasonable. I started it here because it was attached to actual code, but I think we can do that with Jira.

**Comment by joeflack4** [comment]
Thanks for linking that. I didn't have the URL to this Jira project. I'm requesting access to it now.

I think it makes sense to contain as much of the discussion as we can over there on Jira.

But for anything we need to develop at our end, on this codebase or any of our other codebases that we own, it makes sense to continue using GitHub issues for our respective repositories.

**Comment by joeflack4** [comment]
I think we've already begun to do this. @Sigfried If there are any issues here that you think still need to be migrated to Jira, I have access to that now so I can do that if you want. But I think (at first glance) the remaining issues here are just on our end.
