### ISSUE TITLE
New outputs: GRAVITY value sets

### ISSUE THREAD

**Issue by joeflack4** [HOT-Ecosystem/ValueSet-Tools#24]
## Description
Allow `vsac_wrangler` to fetch from the `Lisa2 VSAC GRAVITY` sheet in this GoogleSheets spreadsheet: https://docs.google.com/spreadsheets/d/1jzGrVELQz5L4B_-DqPflPIcpBaTfJOUTrVJT5nS_j18/edit#gid=1272275514

## Related
#42

**Comment by Sigfried** [comment]
@stephanieshong and @joeflack4, where are we with these? Are these all separate from the Lisa1 value sets? Do they still need to be added? I just went through all the grouping sets and except for one, they're fine. They include codes from one or more code systems, but all the codes I checked, including a bunch from CPT4 and a few from HCPCS Level II, are standard concepts, so no need for mapping. And, _I think_, no need for splitting into two concept sets.

**Comment by joeflack4** [comment]
@Sigfried , RE:
> where are we with these? Are these all separate from the Lisa1 value sets?

I/we've been trying to collect all the data sources we're pulling from in `data/cset.csv`. I guess this is another good reason to have a persistence layer for our project, in addition to the internal IDs in there.

The "gravity" value sets are all the rows that have this listed as the source:
https://docs.google.com/spreadsheets/d/1jzGrVELQz5L4B_-DqPflPIcpBaTfJOUTrVJT5nS_j18/edit#gid=1272275514

I guess it would be useful to have a "comments" column or something where we could write in details so that we don't have to manually open these URLs just to see what they are.

---

However now, the sheet name at the [URL I linked above](https://docs.google.com/spreadsheets/d/1jzGrVELQz5L4B_-DqPflPIcpBaTfJOUTrVJT5nS_j18/edit#gid=1272275514) is called "Lisa2 VSAC GRAVITY old". I don't know where the "gravity new" is, if it exists. @Leskena2 do you know?

**Comment by joeflack4** [comment]
@Sigfried Is this done? If so can we close?

**Comment by Sigfried** [comment]
Yes

**Comment by stephanieshong** [comment]
There were some issues with the gravity concept set where the codes are missing from Athena. We were going to meet this week to talk about them I believe.

**Comment by joeflack4** [comment]
Maybe it is better to close this one and open one where we compile the list of problematic sets / codes that are missing. But I'm not working on that stuff at the moment, so however you guys want to handle is fine w/ me~

**Comment by Leskena2** [comment]
Let’s close it. There is already another open issue for the missing codes.

From: Joe Flack ***@***.***>
Date: Monday, March 28, 2022 at 2:15 PM
To: HOT-Ecosystem/ValueSet-Tools ***@***.***>
Cc: Lisa Eskenazi ***@***.***>, Mention ***@***.***>
Subject: Re: [HOT-Ecosystem/ValueSet-Tools] New outputs: GRAVITY value sets (Issue #24)

      External Email - Use Caution





Maybe it is better to close this one and open one where we compile the list of problematic sets / codes that are missing. But I'm not working on that stuff at the moment, so however you guys want to handle is fine w/ me~

**Comment by joeflack4** [comment]
@Leskena2 Thanks for chiming in, Lisa! Closing now.
