### ISSUE TITLE
Delete `[VSAC Bulk-Import test]` sets previously uploaded

### ISSUE THREAD

**Issue by joeflack4** [HOT-Ecosystem/ValueSet-Tools#33]
We previously uploaded a bunch of concept sets whose `concept_set_name`s started with: `[VSAC Bulk-Import test]`

After we've uploaded our next round of concept sets, which start with just `[VSAC]`, we'll want to delete those previously uploaded sets.

**Comment by stephanieshong** [comment]
We need to get the Enclave api that allows us to delete. We currently do not have a method to delete or update via the REST API. It may exist, but currently not exposed us to use. Will ask Amin how to proceed.

**Comment by joeflack4** [comment]
@stephanieshong Sounds good. I started a thread about this on Slack. You might want to check Amin's responses: https://cd2h.slack.com/archives/C034EG5ESU9/p1645559866024859?thread_ts=1645486660.103879&cid=C034EG5ESU9

I did it in a new channel I created called `concept-set-editor-api`. Idk if it was useful for me to do that, but w/e.

**Comment by joeflack4** [comment]
Closing; Stephanie let me know that REST call isn't available to do this, but she did this manually in the enclave UI.
