### ISSUE TITLE
`output/` directory structure

### ISSUE THREAD

**Issue by joeflack4** [HOT-Ecosystem/ValueSet-Tools#39]

**Comment by Sigfried** [comment]
Folder name like `root/output/<source-name>/<date>/` to hold three files:
 - `code_sets`
 - `concept_set_container_edited`
 - `concept_set_version_item_rv_edited`

**Comment by joeflack4** [comment]
@Sigfried Feel free to edit the OP (original post).

I was thinking the structure should change to something like:
`output/palantir-something-something/YYYY-MM-DD/...`
Where `...` will be 3 folders:
- `code_sets`
-

**Comment by joeflack4** [comment]
Also, we might be able to just delete these:
- `output/daveras30`
- `output/normalized`
- `output/vsac_csv`

Not sure we're using these anymore for anything? I think we decided we didn't need a 'normalized' value set schema (independent of both VSAC, enclave, etc), at least not yet?

**Comment by Sigfried** [comment]
Not quite, but howabout:

`data/palantir-three-file/<source-name>/<date>/`
`data/vsac/oid_integer_id_lookup.csv` (was `data/cset.cvs`)
