### ISSUE TITLE
Some concept set names contained space at the end. 

### ISSUE THREAD

**Issue by stephanieshong** [HOT-Ecosystem/ValueSet-Tools#46]
We need to strip off the spaces at the end of the concept set name. Adding as item here before I forget.

**Comment by joeflack4** [comment]
Thank you, Stephanie. Can you or Siggie handle? If you need help, let me know.

**Comment by Sigfried** [comment]
Fixed in the validation program, but the code I used there needs to be moved to the enclave_wrangler.

**Comment by stephanieshong** [comment]
I can change the code in the enclave_wrangler.

**Comment by stephanieshong** [comment]
Just needed to leave a note to myself so I do not forget.

**Comment by stephanieshong** [comment]
resolved in the enclave_wrangler.

**Comment by stephanieshong** [comment]
closing. it is done on the enclave_wrangler side.
