### ISSUE TITLE
Save codeset_id from csets we upload to enclave

### ISSUE THREAD

**Issue by Sigfried** [HOT-Ecosystem/ValueSet-Tools#48]
## Related issues
#47

**Comment by stephanieshong** [comment]
The codeset_id is not saved in the csets as well as in the code_set.csv

**Comment by joeflack4** [comment]
Hey Stephanie~. Thanks for closing, but I'm just a little confused. You mentioned that `codeset_id` is not there, but you closed the issue?

Just for reference, `codeset_id` is in the `Lisa3/.../code_sets.csv`: https://github.com/HOT-Ecosystem/ValueSet-Tools/blob/master/data/palantir-three-file/Lisa3/2022.03.02/output/code_sets.csv

It's also in `cset.csv`, but it's not called `codeset_id`; it's still called `internal_id`: https://github.com/HOT-Ecosystem/ValueSet-Tools/blob/master/data/cset.csv

You can see where I JOINed `codeset_id` on `internal_id` here: https://github.com/HOT-Ecosystem/ValueSet-Tools/blob/20641e3c80bd08e79eb64dd6be659edc172159c1/enclave_wrangler/main.py#L261

**Comment by stephanieshong** [comment]
oh, I meant to say it is saved now.  They are not being saved in code_sets.csv and cset.csv Sorry for the confusion.

**Comment by joeflack4** [comment]
oh I see haha
