### ISSUE TITLE
new enclave_wrangler bug

### ISSUE THREAD

**Issue by Sigfried** [HOT-Ecosystem/ValueSet-Tools#64]
I'm getting a new error while trying to run `enclave_wrangler` for Lisa6, which has a single oid. I put the error message in the commit comment for https://github.com/HOT-Ecosystem/ValueSet-Tools/commit/fdfe3cfc0e47a2ba0e662797857e6ce7c4e8a213

**Comment by joeflack4** [comment]
Just adding an update: Amin gave Stephanie a new parameter to use, but we're still getting this error. We're currently waiting on Amin to look into it and get back to us.

**Comment by stephanieshong** [comment]
Post API call to create the CS container is returning the following error code: 'errorCode': 'PERMISSION_DENIED', 'errorName': 'Phonograph2:PermissionDenied'. Passed on the information to Amin. He will look into this and will let us know.

**Comment by stephanieshong** [comment]
waiting on Amin to fix the error on the container level: {'errorCode': 'PERMISSION_DENIED', 'errorName': 'Phonograph2:PermissionDenied', 'errorInstanceId': '14ceb4b7-a296-4cf9-a94b-ad99a56f3274', 'parameters': {}}

**Comment by stephanieshong** [comment]
The PERMISSION_DENIED error is fixed, however, passing in the authority parameter is returning the following error:
{'errorCode': 'INVALID_ARGUMENT', 'errorName': 'Conjure:UnprocessableEntity', 'errorInstanceId': '293d4002-6b93-464a-ab55-d40384e31fdc', 'parameters': {}}
New parameter:
"ri.actions.main.parameter.f6766c2d - 79a6 - 445f - a664 - d245e1abf199": {
    "type": "string",
    "string": authority
}  # authority source

**Comment by stephanieshong** [comment]
API is updated to pass in the authority parameter : "ri.actions.main.parameter.f6766c2d-79a6-445f-a664-d245e1abf199": {
"type": "string",
"string": authority
} # authority source
The bug resolved.
